# Travis CI configuration
#
# Environment info
# https://docs.travis-ci.com/user/reference/overview/
# https://docs.travis-ci.com/user/reference/osx/
# https://docs.travis-ci.com/user/reference/trusty/

language: c

# macos dependency install
addons:
  homebrew:
    packages:
    - gcc@7
    - yaml-cpp
    - hdf5
    update: true

before_install:
    # mac configuration
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi

    # linux configuration
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install gfortran libblas-dev liblapack-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libopenmpi-dev libyaml-cpp-dev libhdf5-dev libxml2-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv shell 3.7.1; fi

    # common configuration
    - pip3 install numpy

install:
    - mkdir build && cd build
    - cmake .. -DBUILD_TESTING=ON -DDOUBLE_PRECISION=$DOUBLE_PRECISION -DBUILD_SHARED_LIBS=ON -DBUILD_OPENFAST_CPP_API=ON
    - make -j8 install

matrix:
  include:
    - os: linux
      dist: bionic
      env: FC=/usr/bin/gfortran-7; DOUBLE_PRECISION=ON
    - os: linux
      dist: bionic
      env: FC=/usr/bin/gfortran-7; DOUBLE_PRECISION=OFF
    - os: osx
      osx_image: xcode9.2
      env: FC=/usr/local/bin/gfortran-7; DOUBLE_PRECISION=ON
    - os: osx
      osx_image: xcode9.2
      env: FC=/usr/local/bin/gfortran-7; DOUBLE_PRECISION=OFF

script:
    # beamdyn unit tests
    - if [[ "$DOUBLE_PRECISION" == "ON" ]]; then ctest -VV -R beamdyn_utest; fi

    # beamdyn regression tests
    - if [[ "$DOUBLE_PRECISION" == "ON" ]]; then ctest -VV -R bd_; fi

    # subset of openfast regression tests
    # do not run
    # - 3, 4, 7, 15, 16, 17 since the free yaw is not well trusted
    # - 20, 21 because theyre too long
    # THIS IS COMMENTED UNTIL TESTS CAN RELIABLY DETERMINE REGRESSION
    # CURRENTLY, TESTS FAIL WITH VERY MINOR DIFFERENCES
    # - ctest -VV -j 18 -I 1,1,1,2,5,6,8,9,10,11,12,13,14,18,19,22,23,24,25,26
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ctest -j 18 -I 1,1,1,2,5,6,8,9,10,11,12,13,14,18,19,22,23,24,25,26 ; fi

